# 🎓 Análise de Dados do ProUni
Este notebook realiza a análise da base de dados de cursos, mensalidades e bolsas do ProUni.

In [4]:
import pandas as pd

In [7]:
df_prouni = pd.read_excel('/content/cursos-prouni.csv.xlsx')
df_prouni

,grau,turno,mensalidade,bolsa_integral_cotas,bolsa_integral_ampla,bolsa_parcial_cotas,bolsa_parcial_ampla,curso_id,curso_busca,cidade_busca,uf_busca,cidade_filtro,universidade_nome,campus_nome,campus_external_id,nome,nota_integral_ampla,nota_integral_cotas,nota_parcial_ampla,nota_parcial_cotas
0,Bacharelado,Integral,9999.99,15.0,14.0,NaN,NaN,706710394154,Medicina,Campo Grande,MS,NTAwMjAwNDAyNzA0,Universidade Anhanguera - UNIDERP,CAMPO GRANDE - SEDE - Miguel Couto,706710,Medicina,740.22,726.46,NaN,NaN
1,Bacharelado,Noturno,9836.40,1.0,NaN,NaN,NaN,104191210567043,Enfermagem,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Enfermagem,663.36,NaN,NaN,NaN
2,Bacharelado,Integral,9715.61,2.0,5.0,6.0,10.0,1002328574024,Medicina,Sao Paulo,SP,MzUxNTA2MTUwMzA4,Universidade Cidade de São Paulo - UNICID,UNIVERSIDADE CIDADE DE SÃO PAULO - UNICID - SE...,1002328,Medicina,739.62,738.08,738.96,718.64
3,Bacharelado,Noturno,9689.34,3.0,2.0,NaN,NaN,104191212798093,Psicologia,Crateus,CE,MjMwNDAxODA0MTAz,Faculdade Princesa do Oeste - FPO,UNIDADE SEDE - São Vicente,1041912,Psicologia,651.00,652.22,NaN,NaN
4,Bacharelado,Integral,9674.34,4.0,1.0,5.0,2.0,65899611932754,Medicina,Rio Branco,AC,MTIwMjAwNDAwNDAx,Faculdade Barão do Rio Branco - FAB,CAMPUS - RIO BRANCO - JARDIM EUROPA II - Jard...,658996,Medicina,758.32,723.94,734.92,711.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41442,Licenciatura,Curso a Distância,149.00,1.0,NaN,NaN,NaN,994312865605,Sociologia,Paraiso do Tocantins,TO,MTcwMTAwNDE2MTA5,Universidade Paulista - UNIP,PARAISO DO TOCANTINS - Centro,9943,Sociologia,502.36,NaN,NaN,NaN
41443,Tecnológico,Curso a Distância,144.00,1.0,2.0,2.0,5.0,65868712869275,Marketing,Sao VIcente,SP,MzUxNTA2MzUxMDA5,Faculdade de São VIcente - FSV,UNIDADE SEDE - Centro,658687,Marketing,533.34,450.00,450.00,450.00
41444,Tecnológico,Vespertino,139.00,1.0,NaN,NaN,NaN,1056445674232,Gestão de Recursos Humanos,Brasilia,DF,NTMwMTAwMTAwMTA4,Centro Universitário Planalto do Distrito Fede...,DF03 - UNIDADE BRASIL CENTRAL - Taguatinga Nor...,1056445,Gestão de Recursos Humanos,580.76,NaN,NaN,NaN
41445,Bacharelado,Curso a Distância,139.00,1.0,NaN,NaN,NaN,96781210935,Serviço Social,Vitoria,ES,MzIwMzAwOTA1MzA5,Universidade Paulista - UNIP,VITORIA I - Barro Vermelho,9678,Serviço Social,548.26,NaN,NaN,NaN
41446,Tecnológico,Curso a Distância,139.00,3.0,1.0,NaN,NaN,200467412868575,Gestão Ambiental,Santarem,PA,MTUwMTAwMjA2ODA3,Universidade Paulista - UNIP,SANTARÉM - Fátima,2004674,Gestão Ambiental,605.32,573.70,NaN,NaN

In [12]:
pd.set_option('display.max_rows', 1000)

In [13]:
df_prouni['curso_busca'].value_counts()

curso_busca
Administração                                                          2754
Pedagogia                                                              2555
Ciências Contábeis                                                     2056
Gestão de Recursos Humanos                                             1595
Educação Física                                                        1528
Serviço Social                                                         1166
Direito                                                                1093
Logística                                                              1042
Processos Gerenciais                                                   1011
Análise e Desenvolvimento de Sistemas                                  1008
Engenharia Civil                                                        906
Matemática                                                              905
Enfermagem                                                              903
História                                                                898
Gestão Comercial                                                        880
Gestão Pública                                                          839
Gestão Financeira                                                       821
Engenharia de Produção                                                  803
Marketing                                                               757
Psicologia                                                              647
Gestão Ambiental                                                        645
Fisioterapia                                                            604
Engenharia Elétrica                                                     598
Teologia                                                                573
Geografia                                                               547
Arquitetura e Urbanismo                                                 537
Gestão da Tecnologia da Informação                                      507
Nutrição                                                                493
Artes VIsuais                                                           456
Farmácia                                                                444
Filosofia                                                               435
Ciências Biológicas                                                     411
Engenharia Mecânica                                                     388
Biomedicina                                                             388
Gestão Hospitalar                                                       358
Comércio Exterior                                                       336
Sistemas de Informação                                                  286
Gestão da Produção Industrial                                           277
Letras - Português e Inglês                                             274
Letras                                                                  271
Gastronomia                                                             269
Odontologia                                                             268
Gestão de Serviços Jurídicos e Notariais                                263
Sociologia                                                              261
Relações Internacionais                                                 252
Estética e Cosmética                                                    243
Secretariado                                                            228
Engenharia de Computação                                                217
Ciências Econômicas                                                     210
Ciência da Computação                                                   208
Letras - Português                                                      203
Comunicação Social - Publicidade e Propaganda                           200
Ciência Política                                                        188
Medicina Veterinária                                                    181
Redes de Computadores                                                   160
Design de Interiores                                                    159
Gestão da Qualidade                                                     154
Letras - Português e Espanhol                                           153
Agronegócio                                                             143
Segurança no Trabalho                                                   140
Química                                                                 139
Gestão de Turismo                                                       134
Jornalismo                                                              133
Letras - Inglês                                                         132
Engenharia Química                                                      125
Medicina                                                                124
Engenharia Ambiental                                                    123
Agronomia                                                               118
Negócios Imobiliários                                                   113
Embelezamento e Imagem Pessoal                                          112
Design Gráfico                                                          107
Radiologia                                                              101
Turismo                                                                  95
Engenharia de Controle e Automação                                       92
Engenharia Ambiental e Sanitária                                         90
Design de Moda                                                           90
Publicidade e Propaganda                                                 89
Design                                                                   87
Física                                                                   79
Jogos Digitais                                                           79
Sistemas para Internet                                                   71
Letras - Língua Portuguesa                                               70
Música                                                                   69
Gestão do Agronegócio                                                    63
Ciências Sociais                                                         62
Engenharia de Software                                                   62
Comunicação Social - Jornalismo                                          62
Banco de Dados                                                           58
Sistema de Informação                                                    55
Gestão de Segurança Privada                                              52
Fonoaudiologia                                                           50
Biblioteconomia                                                          49
Comunicação Social                                                       45
Produção Publicitária                                                    41
Estética e Imagem Pessoal                                                41
Engenharia Agronômica                                                    39
Fotografia                                                               39
Letras - Espanhol                                                        38
Segurança da Informação                                                  36
Produção Multimídia                                                      36
Biologia                                                                 33
Produção Audiovisual                                                     32
Eventos                                                                  32
Engenharia de Produção Mecânica                                          30
Design de Produto                                                        29
Automação Industrial                                                     29
Gestão de Produção Industrial                                            28
Relações Públicas                                                        28
Educação Especial                                                        27
Engenharia de Petróleo                                                   26
Construção de Edifícios                                                  24
Segurança Pública                                                        24
Gestão de Cooperativas                                                   22
Engenharia Mecatrônica                                                   21
Administração Pública                                                    21
Moda                                                                     18
Informática                                                              18
Letras - Libras                                                          18
Engenharia de Alimentos                                                  18
Computação                                                               18
Estética                                                                 16
Petróleo e Gás                                                           16
Engenharia da Computação                                                 16
Engenharia Eletrônica                                                    15
Propaganda e Marketing                                                   15
Hotelaria                                                                15
Secretariado Executivo                                                   14
Rádio, TV e Internet                                                     14
Ciências Aeronáuticas                                                    14
Mecatrônica Industrial                                                   13
Comunicação Institucional                                                13
Gestão e Empreendedorismo                                                12
Farmácia e Bioquímica                                                    12
Terapia Ocupacional                                                      12
Gestão das Organizações do Terceiro Setor                                11
Engenharia                                                               11
Zootecnia                                                                11
Segurança no Trânsito                                                    10
Engenharia Florestal                                                     10
Gestão Empreendedora                                                      9
Ciência Econômica                                                         9
Cinema e Audiovisual                                                      9
Engenharia Biomédica                                                      9
Oftálmica                                                                 8
Gestão Desportiva e de Lazer                                              8
Ciências da Computação                                                    8
Defesa Cibernética                                                        7
Segurança Privada                                                         7
Administração de Recursos Humanos                                         7
Gerenciamento de Redes de Computadores                                    7
Gestão Mercadológica                                                      7
Comunicação Empresarial                                                   7
Produção Gráfica Digital                                                  7
Comunicação e Ilustração Digital                                          7
Serviços Jurídicos e Notariais                                            6
Turismo Receptivo                                                         6
Gestão de Empreendimentos Esportivos                                      6
Engenharia de Materiais                                                   6
Tradutor e Intérprete                                                     6
Gestão Portuária                                                          6
Engenharia Aeronáutica                                                    5
Teatro                                                                    5
Comunicação para Web                                                      5
Multimídia                                                                5
Produção Fonográfica                                                      5
Processos Químicos                                                        5
Pilotagem Profissional de Aeronaves                                       5
Manutenção de Aeronaves                                                   4
Engenharia de Minas                                                       4
Desenho Industrial                                                        4
Pedagogia - Docencia da Educação Infantil/Administração Educacional       4
Alimentos                                                                 4
Engenharia de Bioprocessos e Biotecnologia                                4
Eletrônica Industrial                                                     4
Processamento de Dados                                                    4
Futebol                                                                   4
Comunicação Social - Radio e Televisão                                    4
Engenharia Agrícola e Ambiental                                           4
Dança                                                                     4
Comunicação Social - Cinema                                               3
Engenharia de Automação e Controle                                        3
Biotecnologia                                                             3
Manutenção Industrial                                                     3
Letras - Português e Inglês e Respectivas Literaturas                     3
Secretariado Executivo Trilíngue                                          3
Construção Naval                                                          3
Engenharia de Petróleo e Gás                                              3
Podologia                                                                 3
Fabricação Mecânica                                                       3
Comunicação Social - Relações Públicas                                    3
Estética, Beleza e Imagem Pessoal                                         2
Engenharia Aeronáutica e Espaço                                           2
Comunicação Social - Cinema e Mídias Digitais                             2
Visagismo e Terapias Capilares                                            2
Soldagem                                                                  2
Comunicação Social  - Radialismo                                          2
Tecnólogo em Metalurgia                                                   2
Física Médica                                                             2
Engenharia Eletrônica e de Telecomunicações                               2
Óptica e Optometria                                                       2
Letras Português e Inglês                                                 2
Refrigeração e Climatização                                               2
Música - Canto                                                            2
Engenharia Automotiva                                                     2
Engenharia de Energias                                                    2
Comunicação Social - Radialismo (Rádio e Tv)                              2
Biocombustíveis                                                           2
Letras - Português e Literatura                                           2
Serviços Jurídicos                                                        2
Letras - Língua Portuguesa e Libras                                       2
Design Digital                                                            2
Artes Cênicas                                                             2
Engenharia de Energia                                                     2
Audiovisual                                                               2
Música - Instrumento                                                      2
Ciências Atuariais                                                        2
Secretariado Executivo - Bilíngue                                         2
Engenharia Ambiental e Energias Renováveis                                2
Engenharia Industrial Mecânica                                            2
Viticultura e Enologia                                                    2
Gestão de Varejo                                                          2
Controle de Obras                                                         2
Química Industrial                                                        1
Agropecuária                                                              1
Estudos Sociais                                                           1
Engenharia de Produção e Qualidade                                        1
Letras - Português e Alemão                                               1
Ciências da Religião                                                      1
Gerência de Negócios                                                      1
Gestão de Lojas e Pontos de Vendas                                        1
Gestão de Turismo Receptivo                                               1
Estética e Cosmetologia                                                   1
Comunicação Social - Cinema e Audiovisual                                 1
Engenharia de Telecomunicações                                            1
Serviços Penais                                                           1
Engenharia de Agrimensura                                                 1
Polímeros                                                                 1
Sistemas de Telecomunicações                                              1
Administração de Empresas                                                 1
Música - Cordas                                                           1
Escrita Criativa                                                          1
Educação Artística - Música                                               1
Gestão de Equinocultura                                                   1
Laticínios                                                                1
Produção Cênica                                                           1
Arqueologia                                                               1
Letras - Tradução Português e Inglês                                      1
Ciências Biológicas - Modalidade Médica                                   1
Negócios Internacionais                                                   1
Geoprocessamento                                                          1
Mídias Sociais                                                            1
Turismo e Hotelaria                                                       1
Enfermagem e Obstetrícia                                                  1
Engenharia de Automação e Sistemas                                        1
Marketing e Propaganda                                                    1
Naturologia                                                               1
Engenharia Metalúrgica                                                    1
Oceanografia                                                              1
Design de Animação                                                        1
Química Tecnológica                                                       1
Saúde Coletiva                                                            1
Ontopsicologia                                                            1
Quiropraxia                                                               1

In [14]:
df_prouni['mensalidade'].max()

9999.99

In [19]:
df_prouni.groupby('uf_busca')['mensalidade'].agg(['sum'])

                 sum
uf_busca
AC         115860.96
AL         174775.38
AM         247383.69
AP         126685.35
BA        1602821.25
CE         654150.36
DF         708968.98
ES         512552.58
GO         712595.49
MA         494741.54
MG        2792888.80
MS         362447.15
MT         522513.98
PA         623230.66
PB         415158.12
PE         729083.81
PI         254947.88
PR        2359939.35
RJ        1074994.24
RN         232422.41
RO         306503.46
RR          47574.59
RS        2273590.61
SC        1230707.10
SE         207392.30
SP        6820708.48
TO         201795.80

In [20]:
df_prouni.groupby(['uf_busca', 'curso_busca'])['mensalidade'].agg(['mean'])

                                                       mean
uf_busca curso_busca
AC       Administração                           422.846667
         Análise e Desenvolvimento de Sistemas   360.000000
         Arquitetura e Urbanismo                1111.300000
         Artes VIsuais                           237.000000
         Biblioteconomia                         356.800000
...                                                     ...
TO       Sistema de Informação                   749.500000
         Sistemas de Informação                  939.540000
         Sociologia                              189.500000
         Teologia                                204.250000
         Turismo                                 404.245000

[2715 rows x 1 columns]

In [21]:
df_prouni.groupby(['uf_busca', 'curso_busca'])['mensalidade'].agg(['mean']).sort_values(by= ['uf_busca', 'mean'])

                                                  mean
uf_busca curso_busca
AC       Negócios Imobiliários              170.000000
         Teologia                           189.000000
         Sociologia                         189.500000
         Filosofia                          233.500000
         Artes VIsuais                      237.000000
...                                                ...
TO       Engenharia Ambiental e Sanitária  1251.240000
         Engenharia de Minas               1314.740000
         Medicina Veterinária              2059.575000
         Odontologia                       2193.836000
         Medicina                          7690.156667

[2715 rows x 1 columns]

In [24]:
def duplicabolsa(rows):
    nova_bolsa = rows * 2
    return nova_bolsa

In [26]:
df = df_prouni[['uf_busca', 'curso_busca', 'mensalidade', 'bolsa_integral_ampla']]
df

      uf_busca                 curso_busca  mensalidade  bolsa_integral_ampla
0           MS                    Medicina      9999.99                  14.0
1           CE                  Enfermagem      9836.40                   NaN
2           SP                    Medicina      9715.61                   5.0
3           CE                  Psicologia      9689.34                   2.0
4           AC                    Medicina      9674.34                   1.0
...        ...                         ...          ...                   ...
41442       TO                  Sociologia       149.00                   NaN
41443       SP                   Marketing       144.00                   2.0
41444       DF  Gestão de Recursos Humanos       139.00                   NaN
41445       ES              Serviço Social       139.00                   NaN
41446       PA            Gestão Ambiental       139.00                   1.0

[41447 rows x 4 columns]

In [27]:
df ['nova_bolsa'] = df['bolsa_integral_ampla'].apply(duplicabolsa)
df

/tmp/ipykernel_426/108559265.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df ['nova_bolsa'] = df['bolsa_integral_ampla'].apply(duplicabolsa)

,uf_busca,curso_busca,mensalidade,bolsa_integral_ampla,nova_bolsa
0,MS,Medicina,9999.99,14.0,28.0
1,CE,Enfermagem,9836.40,NaN,NaN
2,SP,Medicina,9715.61,5.0,10.0
3,CE,Psicologia,9689.34,2.0,4.0
4,AC,Medicina,9674.34,1.0,2.0
...,...,...,...,...,...
41442,TO,Sociologia,149.00,NaN,NaN
41443,SP,Marketing,144.00,2.0,4.0
41444,DF,Gestão de Recursos Humanos,139.00,NaN,NaN
41445,ES,Serviço Social,139.00,NaN,NaN
41446,PA,Gestão Ambiental,139.00,1.0,2.0

In [30]:
df['nova_bolsa'] = df['nova_bolsa'].fillna(1)
df

/tmp/ipykernel_426/1723170702.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['nova_bolsa'] = df['nova_bolsa'].fillna(1)

,uf_busca,curso_busca,mensalidade,bolsa_integral_ampla,nova_bolsa
0,MS,Medicina,9999.99,14.0,28.0
1,CE,Enfermagem,9836.40,NaN,1.0
2,SP,Medicina,9715.61,5.0,10.0
3,CE,Psicologia,9689.34,2.0,4.0
4,AC,Medicina,9674.34,1.0,2.0
...,...,...,...,...,...
41442,TO,Sociologia,149.00,NaN,1.0
41443,SP,Marketing,144.00,2.0,4.0
41444,DF,Gestão de Recursos Humanos,139.00,NaN,1.0
41445,ES,Serviço Social,139.00,NaN,1.0
41446,PA,Gestão Ambiental,139.00,1.0,2.0

In [32]:
df['nova_bolsa_lambda'] = df['bolsa_integral_ampla'].apply(lambda x: x * 2)
df

/tmp/ipykernel_426/2094374926.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['nova_bolsa_lambda'] = df['bolsa_integral_ampla'].apply(lambda x: x * 2)

,uf_busca,curso_busca,mensalidade,bolsa_integral_ampla,nova_bolsa,nova_bolsa_lambda
0,MS,Medicina,9999.99,14.0,28.0,28.0
1,CE,Enfermagem,9836.40,NaN,1.0,NaN
2,SP,Medicina,9715.61,5.0,10.0,10.0
3,CE,Psicologia,9689.34,2.0,4.0,4.0
4,AC,Medicina,9674.34,1.0,2.0,2.0
...,...,...,...,...,...,...
41442,TO,Sociologia,149.00,NaN,1.0,NaN
41443,SP,Marketing,144.00,2.0,4.0,4.0
41444,DF,Gestão de Recursos Humanos,139.00,NaN,1.0,NaN
41445,ES,Serviço Social,139.00,NaN,1.0,NaN
41446,PA,Gestão Ambiental,139.00,1.0,2.0,2.0

In [34]:
df = df.assign(nova_bolsa_lambda2 = lambda x : (x['bolsa_integral_ampla'] * 2))
df

,uf_busca,curso_busca,mensalidade,bolsa_integral_ampla,nova_bolsa,nova_bolsa_lambda,nova_bolsa_lambda2
0,MS,Medicina,9999.99,14.0,28.0,28.0,28.0
1,CE,Enfermagem,9836.40,NaN,1.0,NaN,NaN
2,SP,Medicina,9715.61,5.0,10.0,10.0,10.0
3,CE,Psicologia,9689.34,2.0,4.0,4.0,4.0
4,AC,Medicina,9674.34,1.0,2.0,2.0,2.0
...,...,...,...,...,...,...,...
41442,TO,Sociologia,149.00,NaN,1.0,NaN,NaN
41443,SP,Marketing,144.00,2.0,4.0,4.0,4.0
41444,DF,Gestão de Recursos Humanos,139.00,NaN,1.0,NaN,NaN
41445,ES,Serviço Social,139.00,NaN,1.0,NaN,NaN
41446,PA,Gestão Ambiental,139.00,1.0,2.0,2.0,2.0